### ISSUE TITLE
how it is looks like?

### ISSUE THREAD

**Issue by osvalr** [muhbaasu/doxygen-modern#2]
Hi I would like to see how it looks, would you mind to put a preview on readme?

Thanks

**Comment by marcelbuesing** [comment]
@osvalr there is a link to a documentation using the template in the project title (http://muhbaasu.github.io/doxygen-modern/index.html). I have to admit though it is easy to miss I'll add a screenshot and the link in the README itself.

![example_packages](https://cloud.githubusercontent.com/assets/5637837/14664902/42e721e2-06cf-11e6-9b33-b62b38b7e729.png)

**Comment by osvalr** [comment]
thank you @marcelbuesing
